theme = "default-themes"

[editor]
true-color = true
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
bufferline = "always"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

