[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }
inlayHints.bindingModeHints.enable = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "toml"
language-server = { command = "" }

